datamart/__init__.py
from app import create_app

datamart/app.py
from .extensions import db
from .extensions import mail
from .extensions import data_files
from .extensions import security
from . import models
from .api import manager
from .api import preprocessors
from .api import auth_func
from .api import facts_preprocessors
from .api import facts_postprocessors
from .api import get_single_variable_preprocessor
from .api import get_many_variables_preprocessor
from .api import admin_only_proprocessors
from .jinja_filters import remove_invalid_vars
from .config import DefaultConfig
from flask.ext.uploads import configure_uploads
from flask_debugtoolbar import DebugToolbarExtension
from flask import Flask
from flask.ext.security import SQLAlchemyUserDatastore
from .views import datamart
from .views import render_template_with_login
import os

DEFAULT_BLUEPRINTS = (
    datamart,
)

def create_app(config=None, app_name=None, blueprints=None):
    """Create a Flask app."""

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name, instance_path=DefaultConfig.INSTANCE_FOLDER_PATH, instance_relative_config=True)
    configure_app(app, config)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_error_handlers(app)
    configure_jinja_filters(app)
    configure_api(app)

    return app

def configure_app(app, config=None):
    """Different ways of configurations."""

    # http://flask.pocoo.org/docs/api/#configuration
    app.config.from_object(DefaultConfig)

    # http://flask.pocoo.org/docs/config/#instance-folders
    app.config.from_pyfile('production.cfg', silent=True)

    if config:
        app.config.from_object(config)

    if app.config["DEBUG"]:
        toolbar = DebugToolbarExtension(app)

    # Use instance folder instead of env variables to make deployment easier.
    #app.config.from_envvar('%s_APP_CONFIG' % DefaultConfig.PROJECT.upper(), silent=True)

def configure_extensions(app):
    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # SSLify can't be defined without an app
    from flask_sslify import SSLify
    if app.config["SSLIFY_ENABLED"]:
        sslify = SSLify(app)

    # Setup Flask-Security
    # Flask-Security has some weirdness when using factory style.
    # See https://github.com/mattupstate/flask-security/issues/141
    user_datastore = SQLAlchemyUserDatastore(db, models.User, models.Role)
    security._state = security.init_app(app, datastore=user_datastore)
    security.datastore = user_datastore

    # Uploaded data files
    configure_uploads(app, (data_files))

def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing or app.config["DISABLE_LOGGING"]:
        # Skip debug and test mode. Just check standard output.
        return

    import logging
    from logging.handlers import SMTPHandler

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info("testing info.")
    #app.logger.warn("testing warn.")
    #app.logger.error("testing error.")

    mail_handler = SMTPHandler((app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                               app.config['MAIL_USERNAME'],
                               app.config['ADMINS'],
                               'O_ops... %s failed!' % app.config['PROJECT'],
                               (app.config['MAIL_USERNAME'],
                                app.config['MAIL_PASSWORD']))
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(mail_handler)

def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template_with_login("errors/forbidden_page.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template_with_login("errors/page_not_found.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template_with_login("errors/server_error.html"), 500

def configure_jinja_filters(app):
    app.jinja_env.filters['remove_invalid_vars'] = remove_invalid_vars

def configure_api(app):
    # Flask Restless API
    RESULTS_PER_PAGE = 50
    MAX_RESULTS_PER_PAGE = 10000
    manager.init_app(app, flask_sqlalchemy_db=db)

    manager.create_api(models.Dimension, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'], 
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors=preprocessors)
    manager.create_api(models.Variable, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'], 
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors={'GET_SINGLE':[auth_func, get_single_variable_preprocessor],
                                      'GET_MANY':[auth_func, get_many_variables_preprocessor]
                                     })
    manager.create_api(models.Facts, 
                   methods=['GET', 'DELETE'],
                   results_per_page=RESULTS_PER_PAGE,
                   preprocessors=facts_preprocessors,
                   postprocessors=facts_postprocessors)
    manager.create_api(models.Role, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'],
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors=admin_only_proprocessors)
    manager.create_api(models.Event, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'],
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors=preprocessors)
    manager.create_api(models.Source, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'],
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors=preprocessors)
    manager.create_api(models.Subject, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'],
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors=admin_only_proprocessors)
    manager.create_api(models.ExternalID, 
                       methods=['GET', 'POST', 'DELETE', 'PUT'],
                       results_per_page=RESULTS_PER_PAGE,
                       preprocessors=preprocessors)

def configure_blueprints(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)

datamart/views.py
from flask import render_template, request, flash, redirect, url_for,\
        jsonify, session, abort, current_app
from . import models
from .extensions import db
from . import forms
from .extensions import data_files
from .forms import RoleForm
from .forms import DimensionForm
from .forms import VariableForm
from .forms import UserForm
from .forms import FileUploadForm
from .forms import Form
from .forms import EventForm
from .forms import SourceForm
from .forms import SubjectForm
from .forms import ExternalIDForm
from .forms import IndvFactForm
from flask.ext.security import login_required, LoginForm, current_user
from flask.ext.restless.views import jsonify_status_code
from wtforms import SelectField
from wtforms import validators
from flask import Response
from admin import admin_required
import csv
import re
import os
import json
import StringIO
from flask import Blueprint

datamart = Blueprint('datamart', __name__, template_folder='templates')

def render_template_with_login(template, **kwargs):
    """Render template with LoginForm if current_user is not authenticated."""
    if not current_user.is_authenticated():
        return render_template(template, login_user_form=LoginForm(), **kwargs)
    else:
        return render_template(template, **kwargs)


def model_view(model, template, model_id=None, filter=None):
    if model_id:
        models_data = [model.query.get_or_404(model_id)]
    else:
        if filter is not None:
            models_data = model.query.filter(filter).all()
        else:
            models_data = model.query.all()
    return render_template_with_login(template, models_data=models_data)

def model_edit(model, template, FormType, redirect_default, model_id=None):
    if model_id:
        model_data = model.query.get_or_404(model_id)
    else:
        model_data = model()

    form = FormType(obj=model_data)
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(model_data)
            db.session.add(model_data)
            db.session.commit()
            flash(model.__tablename__.title() + " updated", "alert-success")
            return form.redirect(redirect_default)
        else:
            flash("Please fix errors and resubmit.", "alert-error")
            return render_template(template, model_data=model_data,
                                   form=form)
    elif request.method == 'GET':
        return render_template(template, model_data=model_data,
                               form=form, next=next)

@datamart.route('/', methods=['GET', 'POST',])
def index():
    return render_template('index.html', login_user_form=LoginForm())

@datamart.route('/dimensions/', methods=['GET'])
@datamart.route('/dimensions/<int:dimension_id>/', methods=['GET'])
@login_required
def dimensions_view(dimension_id=None):
    return model_view(models.Dimension,'dimensions.html',dimension_id)

@datamart.route('/dimensions/add/', methods=['GET', 'POST'])
@datamart.route('/dimensions/<int:dimension_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def dimension_edit(dimension_id=None):
    return model_edit(models.Dimension, 'dimension_edit.html', DimensionForm,
                      'dimensions_view', dimension_id)

@datamart.route('/variables/', methods=['GET'])
@datamart.route('/variables/<int:variable_id>/', methods=['GET'])
@login_required
def variables_view(variable_id=None):
    if len(current_user.approved_variables()) > 0:
        filter_clause = (models.Variable.id.in_(current_user.approved_variables()))
    else:
        filter_clause = (True == False)

    return model_view(models.Variable,
                      'variables.html',
                      model_id=variable_id,
                      filter=filter_clause)

@datamart.route('/variables/add/', methods=['GET', 'POST'])
@datamart.route('/variables/<int:variable_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def variable_edit(variable_id=None):
    return model_edit(models.Variable, 'variable_edit.html', VariableForm,
                      'variables_view', variable_id)

@datamart.route('/roles/', methods=['GET'])
@datamart.route('/roles/<int:role_id>/', methods=['GET'])
@login_required
@admin_required
def roles_view(role_id=None):
    return model_view(models.Role,'roles.html',role_id)

@datamart.route('/roles/add/', methods=['GET', 'POST'])
@datamart.route('/roles/<int:role_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def role_edit(role_id=None):
    return model_edit(models.Role, 'role_edit.html', RoleForm,
                      'roles_view', role_id)

@datamart.route('/users/', methods=['GET'])
@datamart.route('/users/<int:user_id>/', methods=['GET'])
@login_required
@admin_required
def users_view(user_id=None):
    return model_view(models.User,'users.html',user_id)

@datamart.route('/users/add/', methods=['GET', 'POST'])
@datamart.route('/users/<int:user_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def user_edit(user_id=None):
    return model_edit(models.User, 'user_edit.html', UserForm,
                      'users_view', user_id)

@datamart.route('/events/', methods=['GET'])
@datamart.route('/events/<int:event_id>/', methods=['GET'])
@login_required
def events_view(event_id=None):
    return model_view(models.Event,'events.html',event_id)

@datamart.route('/events/add/', methods=['GET', 'POST'])
@datamart.route('/events/<int:event_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def event_edit(event_id=None):
    return model_edit(models.Event, 'event_edit.html', EventForm,
                      'events_view', event_id)

@datamart.route('/sources/', methods=['GET'])
@datamart.route('/sources/<int:source_id>/', methods=['GET'])
@login_required
def sources_view(source_id=None):
    return model_view(models.Source,'sources.html',source_id)

@datamart.route('/sources/add/', methods=['GET', 'POST'])
@datamart.route('/sources/<int:source_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def source_edit(source_id=None):
    return model_edit(models.Source, 'source_edit.html', SourceForm,
                      'sources_view', source_id)


@datamart.errorhandler(404)
def not_found(error=None):
    message = {
            'status': 404,
            'message': 'Not Found: ' + request.url,
    }
    resp = jsonify(message)
    resp.status_code = 404

    return resp


@datamart.route('/facts/add/', methods=['GET', 'POST'])
@datamart.route('/facts/<int:fact_id>/edit/', methods=['GET', 'POST'])
@login_required
@admin_required
def fact_edit(fact_id=None):
    if fact_id:
        fact_data = models.Facts.query.get_or_404(fact_id)
    else:
        fact_data = models.Facts()
        fact_data.values = {}

    if fact_data.values:
        values = [{'variable_id': key, 'value': value} for (key, value) in fact_data.values.items()]
    else:
        values = []
    form = IndvFactForm(subject=fact_data.subject, 
                        event=fact_data.event,
                        values=values)

    subjects = models.Subject.query.order_by(models.Subject.internal_id).all()
    events = models.Event.query.order_by(models.Event.name).all()
    variables = models.variables_by_user()
    var_by_id = dict((str(var.id),var) for var in variables)

    if request.method == 'POST':
        if form.validate_on_submit():
            fact_data.subject_id = form.subject.data.id
            fact_data.event_id = form.event.data.id
            fact_values = {}
            for value in form.values:
                if value.variable_id.data != '':
                    fact_values[str(value.variable_id.data)] = value.value.data

            fact_data.values = fact_values
            db.session.add(fact_data)
            db.session.commit()

            if fact_id:
                flash('Fact updated!','alert-success')
            else:
                flash('New Fact added!', 'alert-success')
            redirect(url_for('datamart.fact_edit', fact_id=fact_data.id))
        else:
            for key in form.errors:
                if key == 'values':
                    for value_dict in form.errors[key]:
                        for value_key in value_dict:
                            for error in value_dict[value_key]:
                                flash("Error: " + error, "alert-error")
                else:
                    for error in form.errors[key]:
                        flash("Error: " + error, "alert-error")

            flash("Please fix errors and resubmit.", "alert-error")
            return render_template('fact_edit.html', 
                                   fact=fact_data,
                                   subjects=subjects,
                                   events=events,
                                   var_by_id=var_by_id,
                                   form=form
                                  )

    return render_template('fact_edit.html', 
                           fact=fact_data,
                           subjects=subjects,
                           events=events,
                           var_by_id=var_by_id,
                           form=form
                          )

@datamart.route('/facts/', methods=['GET'])
@login_required
def facts_view():
    facts = models.Facts.query.all()
    # select role.variables where role.users contains current_user
    variables = db.session.query(models.Variable).join((models.Role, models.Variable.roles))\
            .join((models.User,
                   models.Role.users)).filter(models.Variable.in_use == True,
                                              models.User.id == current_user.id)

    return render_template('facts.html', variables=variables, facts=facts)

@datamart.route('/facts/upload/label/<filename>/', methods=['GET', 'POST'])
@login_required
@admin_required
def label_upload_data(filename=None):
    try:
      with open(data_files.path(filename), 'rb') as csvfile:

datamart/templates/base.html
<!DOCTYPE html>
<html lang="en" class="fuelux">
  <head>
  <title>Datamart - {% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta charset="utf-8">

    <style> body { padding-top: 60px; } </style>

    <link href="http://fuelcdn.com/fuelux/2.2/css/fuelux.css" rel="stylesheet" />
    <link href="http://fuelcdn.com/fuelux/2.2/css/fuelux-responsive.css" rel="stylesheet" />
    <link href="{{ url_for('static',filename='css/chosen.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static',filename='css/custom.css') }}" rel="stylesheet" />

    <!-- SUPPORT FOR IE6-8 OF HTML5 ELEMENTS -->
    <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

    <link rel="shortcut icon" href="{{ url_for('static', filename='ico/favicon.ico') }}">
    <script type="text/javascript">
      var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
      var IS_ADMIN = {% if current_user.is_authenticated() %}{{ current_user.is_admin|tojson|safe }}{% else %}false{% endif %};
    </script>
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{{url_for('datamart.index')}}">Datamart</a>
          <div class="nav-collapse">
            <ul class="nav">
              {%- for endpoint, caption in [
                ('datamart.dimensions_view', 'Dimensions'),
                ('datamart.variables_view', 'Variables'),
                ('datamart.events_view', 'Events'),
                ('datamart.facts_view', 'Facts'),
                ('datamart.sources_view', 'Sources'),
                ] %}
                <li{% if endpoint == request.endpoint %} class=active{% endif %}><a href={{ url_for(endpoint) }}>{{ caption }}</a></li>
              {%- endfor %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Subjects<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  {%- for endpoint, caption in [
                    ('datamart.subjects_view', 'Subjects'),
                    ('datamart.externalIDs_view', 'External IDs'),
                    ] %}
                    <li{% if endpoint == request.endpoint %} class='active'{% endif %}><a href={{ url_for(endpoint) }}>{{ caption }}</a></li>
                  {%- endfor %}
                  </ul>
              </li>
              {% if current_user.is_admin %}
              <li class="divider-vertical"></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  {%- for endpoint, caption in [
                    ('datamart.roles_view', 'Roles'),
                    ('datamart.users_view', 'Users'),
                    ('datamart.upload', 'Upload Facts'),
                    ] %}
                    <li{% if endpoint == request.endpoint %} class='active'{% endif %}><a href={{ url_for(endpoint) }}>{{ caption }}</a></li>
                  {%- endfor %}
                </ul>
              </li> 
              {% endif %}
            </ul>
            {% block navbar_right %}
              {% if current_user.is_authenticated() %}
                <div class='pull-right'>
                  <a class='btn btn-primary' href="{{ url_for('security.logout') }}">Logout {{ current_user.username }}</a>
                </div>
              {% elif request.endpoint != 'security.login' %}
                <form class="navbar-form pull-right" action="{{url_for('security.login')}}" method="post">
                  {{ login_user_form.hidden_tag() }}
                  <input type="email" name='email' class="span2" placeholder="you@example.com">
                  <input type="password" name='password' class="span2" placeholder="Password">
                  <input type="submit" value="Login" class="btn"/>
                </form>
              {% endif %}
            {% endblock navbar_right %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    {% endblock navbar %}

    <div class="container">
      <div id="flash-messages">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert {{ category }}">
          <a class="close" data-dismiss="alert">&#215;</a>
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>

      {% block container_content %}
        {% block footer %}
          <hr>
          <footer>
            <p>&copy; Company 2012 </p>
          </footer>
      {% endblock footer %}

      {% endblock container_content %}
    </div>

    {% block datamart_js_footer %}
    <script type="text/javascript" src="{{url_for('static', filename='js/ext/jquery-1.9.1.js')}}"></script>
    <script src="http://fuelcdn.com/fuelux-imh/2.2/loader.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/ext/chosen.jquery.js')}}"></script>
    <script>
      $(document).ready(function(){
        // Activate Chosen.js for select statements
        $('select').chosen({allow_single_deselect:true});
        // Turn on bootstrap tooltips
        $('a').tooltip(container=true);
      });
    </script>
    {% block page_specific_js %}
    {% endblock page_specific_js %}
    {% endblock datamart_js_footer %}
  </body>
</html>

datamart/templates/event_edit.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field, render_controls %}

{% block title %} {% if model_data.name %} Edit Event {{model_data.name}} {% else %} Add new Event {% endif %} {% endblock %}

{% block container_content %}
<h3>{% if model_data.name %} Edit Event {{model_data.name}} {% else %} Add new Event {% endif %}</h3>
<form class='form-horizontal' action="{{ url_for('datamart.event_edit',event_id=model_data.id) }}" method=post>
  <fieldset>
    {{ form.hidden_tag() }}

    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    {{ render_field(form.sources) }}

    {{ render_controls(form, 'datamart.events_view') }}
  </fieldset>
</form>
{% endblock container_content %}

datamart/templates/roles.html
{% extends "base.html" %}
{% from "_gridhelpers.html" import render_grid_controls %}

{% block title %}Roles{% endblock %}
{% block container_content %}
<h3>Roles</h3>
  <p><a class="btn btn-primary" href="{{url_for('datamart.role_edit')}}">Add Role</a></p>
  <table class="table table-striped table-bordered ">
    <thead>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </thead>
    <tbody>
    {% for role in models_data %}
    <tr id='r_{{role.id}}'>
      <td id='n_{{role.id}}'><a href="{{url_for('datamart.roles_view', role_id=role.id)}}">{{ role.name }}</a></td>
      <td>{{ role.description }}</td>
      {{ render_grid_controls(url_for('datamart.role_edit', role_id=role.id),role.id) }}
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock container_content %}

{% block page_specific_js %}
    <script type="text/javascript" src="{{url_for('static', filename='js/dimension.js')}}"></script>
{% endblock page_specific_js %}

datamart/templates/sources.html
{% extends "base.html" %}
{% from "_gridhelpers.html" import render_grid_controls %}

{% block title %}Sources{% endblock %}
{% block container_content %}
<h3>Sources</h3>
  {% if current_user.is_admin %}
    <p><a class="btn btn-primary" href="{{url_for('datamart.source_edit')}}">Add Source</a></p>
  {% endif %}
  <table class="table table-striped table-bordered ">
    <thead>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th>Events</th>
      <th>Variables</th>
      {% if current_user.is_admin %}
        <th></th>
      {% endif %}
    </thead>
    <tbody>
    {% for source in models_data %}
    <tr id='r_{{source.id}}'>
      <td id='n_{{source.id}}'><a href="{{url_for('datamart.sources_view', source_id=source.id)}}">{{ source.name }}</a></td>
      <td>{{ source.description }}</td>
      <td><a href="{{ source.url }}" target="_blank">{{ source.url }}</a></td>
      <td>{% for event in source.events %}<a href={{url_for('datamart.events_view',event_id=event.id)}}>{{event.name}}</a>{% if not loop.last %}, {% endif %}{% endfor %}</td>
      <td>
        {% for variable in source.variables|remove_invalid_vars %}
          <a href={{url_for('datamart.variables_view',variable_id=variable.id)}}>{{variable.name}}</a>{% if not loop.last %}, {% endif %}
        {% endfor %}
      </td>
      {% if current_user.is_admin %}
        {{ render_grid_controls(url_for('datamart.source_edit', source_id=source.id),source.id) }}
      {% endif %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock container_content %}

{% block page_specific_js %}
    <script type="text/javascript" src="{{url_for('static', filename='js/dimension.js')}}"></script>
{% endblock page_specific_js %}

datamart/templates/user_edit.html
{% extends "base.html" %}
{% from "_formhelpers.html" import render_field, render_controls %}

{% block title %} {% if model_data.username %} Edit User {{model_data.username}} {% else %} Add new User {% endif %} {% endblock %}

{% block container_content %}
<h3>{% if model_data.username %} Edit User {{model_data.username}} {% else %} Add new User {% endif %}</h3>
<form class='form-horizontal' action="{{ url_for('datamart.user_edit',user_id=model_data.id) }}" method=post>
  <fieldset>
    {{ form.hidden_tag() }}

    {{ render_field(form.username) }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ render_field(form.active) }}
    {{ render_field(form.roles) }}
    {{ render_field(form.is_admin) }}

    {{ render_controls(form, 'datamart.users_view') }}
  </fieldset>
</form>
{% endblock container_content %}

datamart/templates/variables.html
{% extends "base.html" %}
{% from "_gridhelpers.html" import render_grid_controls %}

{% block title %} Variables {% endblock %}
{% block container_content %}
  <h3>Variables</h3>
  {% if current_user.is_admin %}
  <p><a class="btn btn-primary" href="{{url_for('datamart.variable_edit')}}">Add Variable</a></p>
  {% endif %}
  <table class="table table-striped table-bordered ">
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>Dimension</th>
      {% if current_user.is_admin %}<th>Roles</th>{% endif %}
      <th>Sources</th>
      <th>In Use</th>
      {% if current_user.is_admin %}<th></th>{% endif %}
    </thead>
    <tbody>
    {% for variable in models_data %}
    <tr id='r_{{variable.id}}'>
      <td>{{ variable.id }}</td>
      <td id='n_{{variable.id}}'>{{ variable.name }}</td>
      <td>{{ variable.description }}</td>
      <td><a href={{ url_for('datamart.dimensions_view', dimension_id=variable.dimension.id) }}>{{ variable.dimension.name }}</a></td>
      {% if current_user.is_admin %}
        <td>{% for role in variable.roles %}
          <a href={{url_for('datamart.roles_view',role_id=role.id)}}>{{role.name}}</a>{% if not loop.last %}, {% endif %}
          {% endfor %}
        </td>
      {% endif %}
      <td>{% for source in variable.sources %}<a href={{url_for('datamart.sources_view',source_id=source.id)}}>{{source.name}}</a>{% if not loop.last %}, {% endif %}{% endfor %}</td>
      <td>{{ variable.in_use }}</td>
      {% if current_user.is_admin %}
        {{ render_grid_controls(url_for('datamart.variable_edit', variable_id=variable.id),variable.id) }}
      {% endif %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock container_content %}

{% block page_specific_js %}
    <script type="text/javascript" src="{{url_for('static', filename='js/dimension.js')}}"></script>
{% endblock page_specific_js %}